export type Mode = "demo" | "live";
export type PermissionKey = "gmailRead" | "gmailFull" | "driveRead" | "driveFull" | "driveWrite" | "calendarRead" | "calendarWrite" | "docsWrite" | "draft" | "send" | "bulkSend";
export type Permissions = Record<PermissionKey, boolean>;
export type TaskStatus = "open" | "in_progress" | "waiting" | "blocked" | "done";
export const DEFAULT_CATEGORIES = ["School", "Clubs", "Networking", "Insight Programs", "Campus Events", "Virtual Events", "Personal/Admin"] as const;
export interface ProviderTaskValues { sourceId: string; itemId: string; version: string; title: string; dueDate?: string; dueTime?: string; state?: string; }
export interface Task { id: string; title: string; status: TaskStatus; priority: "P0" | "P1" | "P2"; plannedDate: string; dueDate?: string; dueTime?: string; estimateMinutes: number; notes: string; agentId?: string; sourceIds: string[]; pinned?: boolean; splittable?: boolean; carryoverCount: number; nextActionDate?: string; completedAt?: string; needsInput?: string; updatedAt?: string; categories?: string[]; nextAction?: string; removedAt?: string; providerState?: string; providerRequirementState?: "verified" | "unknown"; providerApplicabilityState?: "verified" | "unknown"; providerDueDate?: string; providerDueTime?: string; providerValues?: ProviderTaskValues; providerAliases?: string[]; providerConflicts?: string[]; revision?: number; userEditedFields?: string[]; }
export interface TaskHistoryEntry { id: string; taskId: string; at: string; action: "created" | "updated" | "completed" | "removed" | "restored" | "source_updated" | "rolled_over"; before?: Task; after?: Task; sourceId?: string; }
export interface CalendarEvent { id: string; title: string; start: string; end: string; location?: string; calendarId: string; status: "confirmed" | "tentative"; sourceIds: string[]; externalId?: string; }
export interface PlanBlock { id: string; taskId: string; start: string; end: string; pinned: boolean; }
export interface Resource { id: string; name: string; kind: "folder" | "document" | "spreadsheet" | "pdf" | "text"; parentId?: string; url?: string; providerId?: string; tabId?: string; namedRangeId?: string; role?: "reference" | "output"; modifiedAt: string; content?: string; bound?: boolean; mode: Mode; }
export interface AgentMessage { id: string; role: "user" | "assistant"; content: string; createdAt: string; entityIds?: string[]; taskId?: string; }
export interface Agent { id: string; name: string; description: string; color: string; initials: string; status: "attention" | "running" | "updated" | "quiet"; summary: string; pinned: boolean; unread: number; lastActiveAt: string; resourceIds: string[]; workflowIds: string[]; messages: AgentMessage[]; }
export type WorkflowAction = "extract_tasks" | "plan" | "rollover" | "calendar_upsert" | "docs_write" | "draft" | "send" | "campaign";
export interface Workflow { id: string; name: string; intent: string; agentId: string; enabled: boolean; version: number; mode: "manual" | "review" | "automatic"; trigger: "manual" | "interval" | "daily"; query: string; actions: WorkflowAction[]; resourceIds: string[]; calendarId?: string; schedule?: string; timezone: string; recipientIds?: string[]; draftIds?: string[]; campaignIds?: string[]; lastRunAt?: string; }
export interface Draft { id: string; to: string; subject: string; body: string; threadId?: string; externalId?: string; status: "draft" | "queued" | "accepted" | "unknown" | "failed"; mode: Mode; updatedAt: string; }
export interface CampaignRecipient { id: string; email: string; name: string; status: "pending" | "accepted" | "failed" | "unknown" | "excluded"; externalId?: string; error?: string; }
export interface Campaign { id: string; name: string; subject: string; body: string; status: "draft" | "scheduled" | "running" | "paused" | "completed" | "cancelled"; recipients: CampaignRecipient[]; mode: Mode; createdAt: string; scheduledAt?: string; ratePerMinute: number; }
export interface Run { id: string; title: string; description: string; status: "succeeded" | "pending" | "conflict" | "failed" | "unknown"; createdAt: string; agentId?: string; workflowId?: string; mode: Mode; modelCalls: number; tokens: number; apiCalls: number; writes: number; cacheHits: number; sourceIds: string[]; taskId?: string; requestId?: string; conversationId?: string; recipeId?: string; changedResourceIds?: string[]; changedEventIds?: string[]; }
export interface ScanJob { id: string; provider: "gmail" | "drive"; coverage: "selected" | "all"; status: "queued" | "running" | "completed" | "paused" | "failed"; discovered: number; read: number; analyzed: number; skipped: number; failed: number; metadataRead?: number; contentRead?: number; truncated?: number; cursor?: string; createdAt: string; mode: Mode; }
export interface Recipe { id: string; name: string; referenceResourceId: string; destinationFolderId: string; agentId?: string; createdAt: string; }
export interface Conversation { id: string; title: string; agentId?: string; scope: "workspace" | "agent"; messages: AgentMessage[]; attachmentIds: string[]; createdAt: string; updatedAt: string; }
export interface Attachment { id: string; name: string; origin: "local" | "drive"; mimeType: string; byteSize?: number; resourceId?: string; url?: string; content?: string; status: "ready" | "unsupported" | "failed"; error?: string; truncated?: boolean; createdAt: string; mode: Mode; }
export interface SourceObligation { itemId: string; title: string; dueDate?: string | null; dueTime?: string | null; categories?: string[]; nextAction?: string; estimateMinutes?: number; providerState?: string; requirementState?: "verified" | "unknown"; applicabilityState?: "verified" | "unknown"; completed?: boolean; notes?: string; aliases?: string[]; }
export interface DailySource { id: string; provider: "gmail" | "calendar" | "drive" | "upload" | "canvas"; externalId?: string; title: string; text: string; url?: string; resourceId?: string; readAt: string; version?: string; truncated?: boolean; obligations?: SourceObligation[]; }
export interface DailyProviderState { provider: "gmail" | "calendar" | "drive"; status: "not_connected" | "not_enabled" | "idle" | "running" | "complete" | "partial" | "failed"; lastReadAt?: string; discovered: number; read: number; skipped: number; failed: number; error?: string; coverage?: "selected" | "all"; query?: string; }
export interface DailySnapshot { id: string; date: string; timezone: string; createdAt: string; updatedAt: string; mode: Mode; sources: DailySource[]; providers: DailyProviderState[]; taskIds: string[]; receiptIds: string[]; summary: string; newTaskIds?: string[]; changedTaskIds?: string[]; }
export interface DailyConfig { enabled: boolean; time: string; gmailQuery: string; calendarId: string; }
export interface CanvasCoverage { courseId: string; courseName: string; family: "courses" | "assignments" | "quizzes" | "discussions" | "modules" | "module_items"; status: "complete" | "partial" | "failed"; discovered: number; error?: string; }
export interface CanvasConfig { enabled: boolean; time: string; weekday: number; }
export interface CanvasReportItem { id: string; title: string; url: string; courseName: string; state: string; dueAt?: string; discoveredAfterGap?: boolean; }
export interface CanvasReportChange { id: string; title: string; url: string; courseName: string; fields: string[]; before: {dueAt?: string; state: string}; after: {dueAt?: string; state: string}; }
export interface CanvasSnapshot { id: string; createdAt: string; updatedAt: string; status: "complete" | "partial" | "failed"; sources: DailySource[]; coverage: CanvasCoverage[]; newTaskIds: string[]; changedTaskIds: string[]; summary: string; initial?: boolean; report?: {id:string;initial:boolean;newItems:CanvasReportItem[];changedItems:CanvasReportChange[];hasMore:boolean}; }
export interface Connection { provider: "google" | "model"; connected: boolean; configured: boolean; label: string; scopes?: string[]; error?: string; }
export interface Usage { modelCalls: number; inputTokens: number; outputTokens: number; apiCalls: number; cacheHits: number; deterministicActions: number; estimatedCostUsd: number; dailyBudgetUsd: number; }
export interface Settings { timezone: string; workingHoursStart: string; workingHoursEnd: string; rolloverEnabled: boolean; mode: Mode; }
export interface WorkspaceState { version: number; today: string; settings: Settings; permissions: Permissions; tasks: Task[]; events: CalendarEvent[]; plan: PlanBlock[]; resources: Resource[]; agents: Agent[]; workflows: Workflow[]; drafts: Draft[]; campaigns: Campaign[]; runs: Run[]; scans: ScanJob[]; recipes?: Recipe[]; conversations?: Conversation[]; attachments?: Attachment[]; daily?: DailySnapshot; dailyConfig?: DailyConfig; taskHistory?: TaskHistoryEntry[]; canvas?: CanvasSnapshot; canvasConfig?: CanvasConfig; googleContextResetAt?: string; canvasContextResetAt?: string; connections: Connection[]; usage: Usage; processedKeys: string[]; }
export interface ActionRequest { type: string; payload?: Record<string, unknown>; requestId?: string; }
export interface ActionResult { state: WorkspaceState; message: string; entityId?: string; }
export interface ApiError { error: string; code?: string; }
