import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';
import { assignmentSource } from '../../src/lib/canvas/classify';
import { explicitCandidates } from '../../src/lib/server/daily';
import { TaskFeed } from '../../src/components/TaskFeed';
import { applyAction } from '../../src/lib/domain/actions';
import { ingestTaskCandidates } from '../../src/lib/domain/tasks';
import { now, task, workspace } from '../domain/helpers';
import { CanonicalDaily, EventDetail, HomeIndex, TaskDetail, TaskEditor, TaskViews, taskEditPatch } from '../../src/components/TaskWorkspace';
import { CanvasReport } from '../../src/components/Canvas';
import { dailyGroups, parseWorkspaceRoute, taskHref, taskViewHref, viewTasks, type ViewFilters } from '../../src/components/taskViews';
import type { CanvasSnapshot, WorkspaceState } from '../../src/lib/types';
const run=vi.fn(async()=>null);
const screen=(state:WorkspaceState)=>({state,run,busy:null});
function example(){const state=workspace();state.tasks=[task('networking-email',{title:'Follow up on example conversation',categories:['Networking','Clubs'],nextAction:'Draft a short follow-up',dueDate:'2026-10-05',dueTime:'12:00'})];return state;}
const views:ViewFilters[]=[{view:'priority',priority:'P1'},{view:'category',category:'Networking'},{view:'category',category:'Clubs'},{view:'planned',date:'2026-10-03'},{view:'deadline',date:'2026-10-05'}];
function html(state:WorkspaceState,filters:ViewFilters){return renderToStaticMarkup(<TaskViews {...screen(state)} filters={filters} onFilters={()=>{}}/>);}
function canvas(fields:Partial<CanvasSnapshot>={}):CanvasSnapshot{return {id:'synthetic-report',createdAt:now.toISOString(),updatedAt:now.toISOString(),status:'partial',sources:[],coverage:[],newTaskIds:[],changedTaskIds:[],summary:'Fictional coverage report.',...fields};}
describe('canonical UI projections and navigation',()=>{
  it.each(views)('uses the same ID and original object in $view',filters=>{const state=example();expect(viewTasks(state,filters)[0]).toBe(state.tasks[0]);const markup=html(state,filters);expect(markup).toContain('data-task-id="networking-email"');expect(markup).toContain('#task/networking-email?return=');});
  it('completes from a planned view and clears every active mirror with history retained',()=>{const initial=example();const done=applyAction(initial,{type:'task.update',payload:{id:'networking-email',status:'done',expectedVersion:initial.version}},now).state;for(const filter of views){expect(viewTasks(done,filter)).toHaveLength(0);expect(html(done,filter)).not.toContain('data-task-id="networking-email"');}expect(dailyGroups(done).planned).toHaveLength(0);expect(viewTasks(done,{view:'history',history:'completed'})[0].id).toBe('networking-email');expect(done.taskHistory?.some(entry=>entry.taskId==='networking-email'&&entry.action==='completed')).toBe(true);expect(done.runs.some(receipt=>receipt.taskId==='networking-email')).toBe(true);expect(initial.tasks[0].status).toBe('open');const pastDeadlineHistory=structuredClone(done);pastDeadlineHistory.tasks[0].dueDate='2026-10-02';expect(html(pastDeadlineHistory,{view:'history',history:'completed'})).not.toContain(' · overdue');});
  it('retains removal then restores the original ID across every mirror',()=>{const initial=example();const removed=applyAction(initial,{type:'task.delete',payload:{id:'networking-email'}},now).state;for(const filter of views)expect(viewTasks(removed,filter)).toHaveLength(0);expect(removed.tasks[0].removedAt).toBeTruthy();expect(viewTasks(removed,{view:'history',history:'removed'})[0].id).toBe('networking-email');const restored=applyAction(removed,{type:'task.restore',payload:{id:'networking-email'}},now).state;for(const filter of views)expect(viewTasks(restored,filter)[0].id).toBe('networking-email');expect(restored.tasks).toHaveLength(1);});
  it('a second client renders the committed workspace without stale action rows',()=>{const first=example();const committed=applyAction(first,{type:'task.update',payload:{id:'networking-email',status:'done'}},now).state;const secondClient=structuredClone(committed);expect(secondClient.version).toBeGreaterThan(first.version);expect(html(secondClient,{view:'priority',priority:'P1'})).not.toContain('Complete Follow up');expect(html(secondClient,{view:'category',category:'Networking'})).not.toContain('data-task-id="networking-email"');});
  it('moving the planned date changes that view but leaves the hard deadline intact',()=>{const moved=applyAction(example(),{type:'task.update',payload:{id:'networking-email',plannedDate:'2026-10-04'}},now).state;expect(viewTasks(moved,{view:'planned',date:'2026-10-03'})).toHaveLength(0);expect(viewTasks(moved,{view:'planned',date:'2026-10-04'})[0].id).toBe('networking-email');expect(viewTasks(moved,{view:'deadline',date:'2026-10-05'})[0].dueTime).toBe('12:00');});
  it('preserves category/date/search filters through the detail return route',()=>{const filters:ViewFilters={view:'category',category:'Campus Events',query:'example & event',date:'2026-10-03'};const href=taskViewHref(filters);const detail=parseWorkspaceRoute(taskHref('stable/id',href));expect(detail.id).toBe('stable/id');expect(detail.returnTo).toBe(href);expect(parseWorkspaceRoute(detail.returnTo).filters).toEqual(filters);});
  it('restricts the return route to internal workspace views',()=>{expect(parseWorkspaceRoute('#task/one?return=https%3A%2F%2Fexample.com').returnTo).toBe('#home');expect(parseWorkspaceRoute('#task/one?return=%23connections').returnTo).toBe('#home');});
  it.each(['submitted','pending_grading','pending_review','graded','excused','completed'])('keeps provider state %s out of active submission work without claiming local completion',providerState=>{const state=example();state.tasks[0].providerState=providerState;for(const filter of views)expect(viewTasks(state,filter)).toHaveLength(0);expect(state.tasks[0].status).toBe('open');expect(viewTasks(state,{view:'history',history:'provider'})[0].id).toBe('networking-email');});
  it('carries a verified lab deadline with unknown completion from Canvas classification through ingestion into every UI surface',()=>{const classified=assignmentSource({id:1,name:'Fictional in-person lab',submission_types:['on_paper'],published:true,due_at:'2026-10-02T18:00:00Z',description:'<p>Attend the fictional lab.</p>'},{prefix:'canvas:synthetic-owner-account',baseUrl:'https://canvas.example.com',courseId:'10',courseName:'Example course',accountId:'99',timezone:'UTC',now:now.toISOString()})!;expect(classified.source.obligations?.[0]).toMatchObject({dueDate:'2026-10-02',dueTime:'18:00',providerState:'unknown'});const state=ingestTaskCandidates(workspace(),explicitCandidates([classified.source],'2026-10-03'),now);state.settings.timezone='UTC';const item=state.tasks[0];expect(item).toMatchObject({dueDate:'2026-10-02',providerDueDate:'2026-10-02',providerState:'unknown',status:'open'});expect(viewTasks(state,{view:'deadline',date:'2026-10-02'})[0].id).toBe(item.id);expect(dailyGroups(state).deadlines[0].id).toBe(item.id);expect(dailyGroups(state).waiting[0].id).toBe(item.id);expect(dailyGroups(state).planned).toHaveLength(0);const markup=html(state,{view:'deadline'});expect(markup).toContain('Deadline Oct 2');expect(markup).toContain('status unknown');expect(markup).not.toContain(' · overdue');const feed=renderToStaticMarkup(<TaskFeed {...screen(state)} tasks={[item]} editTask={()=>{}} openAgent={()=>{}} onState={()=>{}} onError={()=>{}}/>);expect(feed).toContain('Due Oct 2');expect(feed).toContain('confirm completion or submission');expect(feed).not.toContain('class="text-red"');});
  it('renders all five Daily sections and keeps the fixed event separate',()=>{const state=example();state.events=[{id:'fixed-event',title:'Example attendance window',start:'2026-10-03T09:00:00Z',end:'2026-10-03T10:00:00Z',calendarId:'primary',status:'confirmed',sourceIds:[]}];state.settings.timezone='UTC';const markup=renderToStaticMarkup(<CanonicalDaily {...screen(state)}/>);for(const title of ['Hard deadlines','Planned work','Fixed events','Waiting &amp; blocked','Completed today'])expect(markup).toContain(title);expect(markup).toContain('#event/fixed-event');expect(markup).not.toContain('Complete Example attendance window');});
  it('uses workspace timezone for completed-day history and overlapping events',()=>{const state=example();state.settings.timezone='America/Los_Angeles';state.tasks[0].status='done';state.tasks[0].completedAt='2026-10-04T01:00:00Z';state.events=[{id:'overnight',title:'Event',start:'2026-10-03T05:00:00Z',end:'2026-10-03T09:00:00Z',calendarId:'primary',status:'confirmed',sourceIds:[]}];expect(dailyGroups(state).completed).toHaveLength(1);expect(dailyGroups(state).events).toHaveLength(1);});
  it('keeps future tasks available in planned and category views',()=>{const state=example();state.tasks[0].plannedDate='2026-11-01';expect(viewTasks(state,{view:'planned',date:'2026-11-01'})).toHaveLength(1);expect(viewTasks(state,{view:'category',category:'Networking'})).toHaveLength(1);});
  it('editing one field does not claim ownership of unchanged provider values',()=>{const item=example().tasks[0];expect(taskEditPatch(item,{id:item.id,title:item.title,dueDate:item.dueDate,dueTime:item.dueTime,categories:item.categories,notes:item.notes,nextAction:item.nextAction,priority:'P0',pinned:false,splittable:false,needsInput:'',agentId:'',expectedVersion:4})).toEqual({id:item.id,priority:'P0',expectedVersion:4});});
  it('offers defaults, multiple selections, and custom categories in one editor',()=>{const state=example();state.tasks[0].categories=['Networking','Research'];const markup=renderToStaticMarkup(<TaskEditor {...screen(state)} task={state.tasks[0]} onSaved={()=>{}} onCancel={()=>{}}/>);for(const name of ['School','Clubs','Networking','Insight Programs','Campus Events','Virtual Events','Personal/Admin','Research','New category name'])expect(markup).toContain(name);expect(markup.match(/checked=""/g)?.length).toBe(2);});
  it('supports direct completed/removed/missing task detail routes without recreating records',()=>{const state=example();state.tasks[0].removedAt=now.toISOString();const props={...screen(state),id:'networking-email',returnTo:'#history',onNavigate:()=>{},openAgent:()=>{},onState:()=>{},onError:()=>{}};expect(renderToStaticMarkup(<TaskDetail {...props}/>)).toContain('Restore');expect(renderToStaticMarkup(<TaskDetail {...props} id="missing"/>)).toContain('No replacement record was created');});
  it('waiting rows show the needed decision and follow-up date',()=>{const state=example();state.tasks[0].status='blocked';state.tasks[0].needsInput='Await example teammate approval';state.tasks[0].nextActionDate='2026-10-06';const markup=renderToStaticMarkup(<CanonicalDaily {...screen(state)}/>);expect(markup).toContain('Await example teammate approval');expect(markup).toContain('Follow-up Oct 6');});
  it('task details show exact receipt-linked attachments as escaped source text',()=>{const state=example();state.attachments=[{id:'attachment-1',name:'Synthetic notes.txt',origin:'local',mimeType:'text/plain',status:'ready',mode:'demo',createdAt:now.toISOString(),content:'<script>synthetic source</script>'}];state.runs=[{id:'receipt-1',taskId:state.tasks[0].id,title:'Example task receipt',description:'Synthetic task-linked response',status:'succeeded',createdAt:now.toISOString(),mode:'demo',modelCalls:0,tokens:0,apiCalls:0,writes:0,cacheHits:0,sourceIds:['attachment-1']}];const markup=renderToStaticMarkup(<TaskDetail {...screen(state)} id={state.tasks[0].id} returnTo="#home" onNavigate={()=>{}} openAgent={()=>{}} onState={()=>{}} onError={()=>{}}/>);expect(markup).toContain('Task source attachments');expect(markup).toContain('Synthetic notes.txt');expect(markup).toContain('&lt;script&gt;');expect(markup).not.toContain('<script>');});
  it('home index preserves access to independent chats, Drive, Canvas, and history',()=>{const markup=renderToStaticMarkup(<HomeIndex state={example()}/>);for(const href of ['#daily','#chats','#resources','#canvas','#history'])expect(markup).toContain(`href="${href}"`);});
  it('event details do not offer task completion',()=>{const state=example();state.events=[{id:'event',title:'Example event',start:'2026-10-03T09:00:00Z',end:'2026-10-03T10:00:00Z',calendarId:'primary',status:'confirmed',sourceIds:[]}];const markup=renderToStaticMarkup(<EventDetail state={state} id="event" returnTo="#daily"/>);expect(markup).toContain('Fixed attendance window');expect(markup).not.toContain('Complete Example event');});
  it('provider imports preserve a retained removal instead of recreating an active view',()=>{const source={sourceId:'synthetic-canvas-course-1',itemId:'assignment-1',sourceVersion:'1',title:'Example assignment',plannedDate:'2026-10-03',categories:['School']};const imported=ingestTaskCandidates(workspace(),[source]);const removed=applyAction(imported,{type:'task.delete',payload:{id:imported.tasks[0].id}},now).state;const repeated=ingestTaskCandidates(removed,[{...source,sourceVersion:'2',title:'Changed example assignment'}]);expect(repeated.tasks).toHaveLength(1);expect(viewTasks(repeated,{view:'all'})).toHaveLength(0);});
});
describe('truthful Canvas report presentation',()=>{
  it('shows no-data instructions without invented success',()=>{const markup=renderToStaticMarkup(<CanvasReport state={workspace()}/>);expect(markup).toContain('Your first coursework inventory');expect(markup).not.toContain('Recorded pages complete');});
  it('separates new already-submitted provider items from changed deadlines using exact before/after values',()=>{const state=workspace();state.canvas=canvas({report:{id:'weekly-report',initial:false,hasMore:false,newItems:[{id:'source-new',title:'Already submitted example',url:'https://example.com/synthetic-new',courseName:'Example course',state:'pending_grading',dueAt:'2026-10-05T12:00:00Z',discoveredAfterGap:true}],changedItems:[{id:'source-old',title:'Changed existing assignment',url:'https://example.com/synthetic-old',courseName:'Example course',fields:['dueAt','state'],before:{dueAt:'2026-10-05T12:00:00Z',state:'not_submitted'},after:{dueAt:'2026-10-07T12:00:00Z',state:'submitted'}}]}});state.settings.timezone='UTC';const markup=renderToStaticMarkup(<CanvasReport state={state}/>);for(const text of ['New assignments &amp; obligations','Changed deadlines &amp; statuses','Already submitted example','pending grading','Found after a coverage gap','Oct 5','Oct 7','weekly-report'])expect(markup).toContain(text);expect(markup).not.toContain('Complete Already submitted example');});
  it('exposes a failed middle page and prevents a false complete claim',()=>{const state=workspace();state.canvas=canvas({coverage:[{courseId:'course-1',courseName:'Example course',family:'assignments',status:'partial',discovered:50,error:'Page 3 failed; saved cursor can resume.'}]});const markup=renderToStaticMarkup(<CanvasReport state={state}/>);expect(markup).toContain('Partial or unverified coverage');expect(markup).toContain('Page 3 failed');expect(markup).not.toContain('Recorded pages complete');});
  it('missing family-level coverage is unverified even if a status says complete',()=>{const state=workspace();state.canvas=canvas({status:'complete'});const markup=renderToStaticMarkup(<CanvasReport state={state}/>);expect(markup).toContain('No family-level coverage evidence');expect(markup).not.toContain('Recorded pages complete');});
  it('unfinished pagination stays partial even with currently completed family rows',()=>{const state=workspace();state.canvas=canvas({status:'complete',coverage:[{courseId:'course-1',courseName:'Example course',family:'assignments',status:'complete',discovered:5}],report:{id:'continuing',initial:true,newItems:[],changedItems:[],hasMore:true}});expect(renderToStaticMarkup(<CanvasReport state={state}/>)).not.toContain('Recorded pages complete');});
  it('shows body/submission counts and last successful read separately from metadata discovery',()=>{const state=workspace();state.canvas=canvas({coverage:[{courseId:'course',courseName:'Example course',family:'assignments',status:'partial',discovered:8,metadataRead:8,contentRead:2,submissionRead:1,lastSuccessfulReadAt:now.toISOString(),gaps:['Override applicability unresolved']} as NonNullable<WorkspaceState['canvas']>['coverage'][number]]});const markup=renderToStaticMarkup(<CanvasReport state={state}/>);for(const text of ['8 metadata reads','2 content reads','1 submission reads','Last successful read','Override applicability unresolved'])expect(markup).toContain(text);});
  it('escapes untrusted coursework titles and text',()=>{const state=workspace();state.canvas=canvas({sources:[{id:'source',provider:'canvas',title:'<script>example</script>',text:'<img src=x onerror=example>',readAt:now.toISOString()}]});const markup=renderToStaticMarkup(<CanvasReport state={state}/>);expect(markup).toContain('&lt;script&gt;');expect(markup).not.toContain('<img src=x');});
});
