import { useState, type FormEvent } from 'react';
import { ArrowRight, CalendarDays, Check, ExternalLink, FileText, HardDrive, KeyRound, Link2, Mail, Pause, Play, Plug, RefreshCw, Search, Send, Settings2, ShieldCheck, Sparkles, Unplug, Users, Wallet } from 'lucide-react';
import { api, API_BASE, getOwnerKey, setOwnerKey } from '../lib/client';
import type { PermissionKey } from '../lib/types';
import { Badge, Button, Field, Modal, money, Toggle, type ScreenProps } from './ui';
const permissionGroups: { title: string; description: string; items: { key: PermissionKey; name: string; text: string; broad?: boolean }[] }[] = [
  { title:'Read & understand', description:'Decide which source material your agents can access.', items:[
    {key:'gmailRead',name:'Read Gmail',text:'Read selected messages and threads for your workflows.'},
    {key:'gmailFull',name:'Broad Gmail access',text:'Allow full-mailbox discovery and resumable scans.',broad:true},
    {key:'driveRead',name:'Read Google Drive',text:'Browse and read selected files and bound references.'},
    {key:'driveFull',name:'Broad Drive access',text:'Allow discovery and scanning across accessible Drive files.',broad:true},
  ]},
  {title:'Create & update', description:'Give agents specific places to contribute.',items:[
    {key:'calendarWrite',name:'Write calendar events',text:'Create or update events through explicit actions and workflows.'},
    {key:'driveWrite',name:'Create documents from templates',text:'Copy a reference into an explicitly bound Drive folder. Live recipes also require Docs write permission.'},
    {key:'docsWrite',name:'Write Google Docs',text:'Write content to bound output documents.'},
    {key:'draft',name:'Create email drafts',text:'Prepare and edit messages for review. This does not allow sending.'},
  ]},
  {title:'Send & reach out',description:'Sending stays separate from reading and drafting.',items:[
    {key:'send',name:'Send individual emails',text:'Allow reviewed messages to be sent through Gmail.'},
    {key:'bulkSend',name:'Send campaigns',text:'Allow campaign queues to dispatch. Individual send must also be enabled.',broad:true},
  ]},
];
export function Connections({state,run,busy,refresh}:ScreenProps & {refresh:()=>Promise<void>}) {
  const [connecting,setConnecting] = useState(false);
  const [connectionError,setConnectionError] = useState<string|null>(null);
  const [connectionMessage,setConnectionMessage] = useState<string|null>(null);
  const [authorizationUrl,setAuthorizationUrl] = useState<string|null>(null);
  const [ownerKey,setKey] = useState('');
  const [ownerActive,setOwnerActive] = useState(!!getOwnerKey());
  const [ownerLoading,setOwnerLoading] = useState(false);
  const [scanOpen,setScanOpen] = useState(false);
  const [disconnect,setDisconnect] = useState(false);
  const [reset,setReset] = useState(false);
  const google = state.connections.find(c=>c.provider==='google');
  const model = state.connections.find(c=>c.provider==='model');
  const gmailScans = state.scans.filter(s=>s.provider==='gmail').slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,2);
  async function connectGoogle() { setConnecting(true); setConnectionError(null); setAuthorizationUrl(null); try { const result=await api<{url:string}>('/api/google/authorize', {method:'POST',body:'{}'}); const url=new URL(result.url); const apiOrigin=new URL(API_BASE || window.location.origin).origin; const localLaunch=['localhost','127.0.0.1'].includes(url.hostname) && ['localhost','127.0.0.1'].includes(window.location.hostname); if(!['https:',...(localLaunch?['http:']:[])].includes(url.protocol) || (url.origin!==apiOrigin && !localLaunch) || !url.pathname.endsWith('/api/google/authorize')) throw new Error('The backend returned an unexpected authorization URL.'); setAuthorizationUrl(url.href); setConnectionMessage('Your Google authorization link is ready. Continue within 60 seconds, then refresh connection status when you return.'); } catch(e) {setConnectionError(e instanceof Error?e.message:'Could not start Google authorization.');} finally {setConnecting(false);} }
  async function saveOwnerKey(e:FormEvent<HTMLFormElement>) { e.preventDefault(); setOwnerLoading(true); setConnectionError(null); const previous=getOwnerKey(); setOwnerKey(ownerKey.trim()); try {await api('/api/google/status'); await refresh(); setOwnerActive(true); setKey(''); setConnectionMessage('Owner key applied for this browser session.');} catch(e) {setOwnerKey(previous);setConnectionError(e instanceof Error?e.message:'Could not unlock owner access.');} finally {setOwnerLoading(false);} }
  async function saveSettings(e:FormEvent<HTMLFormElement>) {e.preventDefault(); const fd=new FormData(e.currentTarget); await run('settings.update',{timezone:fd.get('timezone'),workingHoursStart:fd.get('workingHoursStart'),workingHoursEnd:fd.get('workingHoursEnd')});}
  return <>
    <div className="page-heading"><div><div className="eyebrow"><Plug size={14}/>CONNECTED, ON YOUR TERMS</div><h1>You set the boundaries<span className="heading-dot">.</span></h1><p>Connect your tools. Choose your permissions. Keep the final say.</p></div><Badge tone={state.settings.mode==='live'?'green':'orange'} dot>{state.settings.mode==='live'?'Live workspace':'Demo workspace'}</Badge></div>
    <div className="connections-grid"><div className="connections-main">
      <section className="panel connection-panel"><div className="panel-head"><div><h2>Your connected tools</h2><p>Account access and workspace permissions are separate.</p></div><button className="icon-button" aria-label="Refresh connection status" onClick={()=>void refresh()}><RefreshCw size={16}/></button></div><div className="provider-row"><span className="provider-icon google-icon"><HardDrive size={24} strokeWidth={1.5}/></span><div className="provider-details"><h3>Google Workspace<Badge tone={google?.connected?'green':'neutral'} dot>{google?.connected?'Connected':google?.configured?'Ready to connect':'Setup needed'}</Badge></h3><p>Gmail, Drive, Calendar & Docs</p>{google?.error&&<p className="text-red">{google.error}</p>}</div>{google?.connected?<Button onClick={()=>setDisconnect(true)}><Unplug size={14}/>Disconnect</Button>:<Button onClick={()=>void connectGoogle()} loading={connecting} disabled={connecting}><Link2 size={14}/>Connect Google</Button>}</div>{google?.scopes?.length ? <details className="scope-details"><summary>View granted OAuth scopes ({google.scopes.length})</summary><ul>{google.scopes.map(scope=><li key={scope}>{scope}</li>)}</ul></details>:null}<div className="provider-row"><span className="provider-icon model-icon"><Sparkles size={24} strokeWidth={1.5}/></span><div className="provider-details"><h3>Model intelligence<Badge tone={model?.connected?'green':'neutral'} dot>{model?.connected?'Configured':'Not configured'}</Badge></h3><p>{model?.label||'Optional model-backed conversations and reasoning'}</p>{model?.error&&<p className="text-red">{model.error}</p>}</div><Badge>{state.settings.mode==='demo'?'Model-free demo':'Server configured'}</Badge></div><div className="connection-explainer"><ShieldCheck size={16}/><span>Credentials stay on the backend. Permission switches do not grant new Google OAuth scopes; reconnect when additional consent is required.</span></div>{connectionError&&<div className="inline-alert" role="alert">{connectionError}</div>}{connectionMessage&&<p className="connection-message" role="status">{connectionMessage}</p>}{authorizationUrl&&<a className="button button-primary google-continue" href={authorizationUrl} target="_blank" rel="noopener noreferrer">Continue to Google<ExternalLink size={15}/></a>}</section>
      <section className="panel permission-panel"><div className="panel-head"><div><span className="eyebrow">CAPABILITIES</span><h2>Precisely as much access as you choose</h2><p>Changes apply to new actions and queued sends.</p></div><ShieldCheck size={22} className="muted"/></div>{permissionGroups.map(group=><div className="permission-group" key={group.title}><div className="permission-group-heading"><h3>{group.title}</h3><p>{group.description}</p></div>{group.items.map(item=><div className="permission-row" key={item.key}><div><strong>{item.name}{item.broad&&<Badge tone="orange">Broad access</Badge>}</strong><p>{item.text}</p></div><Toggle checked={state.permissions[item.key]} label={item.name} disabled={!!busy} onChange={()=>void run('permissions.update',{[item.key]:!state.permissions[item.key]})}/></div>)}</div>)}</section>
      <section className="panel gmail-scan-panel"><div className="panel-head"><div><h2>Mailbox coverage</h2><p>Broad reading should never be a black box.</p></div><div className="button-group"><Button disabled={!!busy||!state.permissions.gmailRead} onClick={()=>void run('sync.run',{provider:'gmail'})}><RefreshCw size={14}/>Sync</Button><Button onClick={()=>setScanOpen(true)}><Search size={14}/>Scan Gmail</Button></div></div>{gmailScans.length?gmailScans.map(job=><div className="mailbox-scan" key={job.id}><div><strong>{job.coverage==='all'?'Full mailbox':'Selected messages'}</strong><Badge tone={job.status==='completed'?'green':job.status==='failed'?'red':'orange'}>{job.status}</Badge><Badge>{job.mode}</Badge></div><div className="progress-track"><i style={{width:`${job.discovered?Math.min(100,job.read/job.discovered*100):0}%`}}/></div><div className="mailbox-scan-stats"><span>{job.discovered} discovered</span><span>{job.read} read</span><span>{job.analyzed} analyzed</span><span>{job.skipped} skipped</span><span>{job.failed} failed</span>{['running','queued','paused'].includes(job.status)&&<Button variant="ghost" disabled={!!busy} onClick={()=>void run(job.status==='paused'?'scan.resume':'scan.pause',{id:job.id})}>{job.status==='paused'?<Play size={13}/>:<Pause size={13}/>} {job.status==='paused'?'Resume':'Pause'}</Button>}</div></div>):<p className="compact-empty">No mailbox scans yet. Choose selected messages or enable broad Gmail access for full coverage.</p>}</section>
    </div><aside className="settings-aside"><section className="panel settings-card"><div className="settings-card-heading"><Settings2 size={19}/><h2>Workspace mode</h2></div><div className="mode-options"><button className={state.settings.mode==='demo'?'mode-selected':''} disabled={!!busy} onClick={()=>void run('settings.update',{mode:'demo'})}><span>Demo{state.settings.mode==='demo'&&<Check size={14}/>}</span><small>Synthetic data. Simulated actions.</small></button><button className={state.settings.mode==='live'?'mode-selected':''} disabled={!!busy} onClick={()=>void run('settings.update',{mode:'live'})}><span>Live{state.settings.mode==='live'&&<Check size={14}/>}</span><small>Connected services. Real actions.</small></button></div><p className="settings-help">Live mode requires owner access and configured services. Missing connections surface an error.</p></section>
    <section className="panel settings-card"><div className="settings-card-heading"><KeyRound size={19}/><h2>Owner access</h2></div><p className="settings-help">Use the backend owner key to access the live workspace. It stays in memory for this tab and clears on reload.</p>{ownerActive?<><Badge tone="green" dot>Owner key applied</Badge><Button className="full-width" onClick={async()=>{setOwnerKey('');setOwnerActive(false);setConnectionMessage('Owner key cleared. Loading your demo workspace.');await refresh();}}>Clear owner key</Button></>:<form onSubmit={saveOwnerKey} className="small-form"><Field label="Owner access key"><input type="password" value={ownerKey} onChange={e=>setKey(e.target.value)} autoComplete="off" required placeholder="Enter your owner key"/></Field><Button type="submit" loading={ownerLoading} disabled={ownerLoading||!ownerKey.trim()}><KeyRound size={14}/>Apply key</Button></form>}</section>
    <section className="panel settings-card"><div className="settings-card-heading"><CalendarDays size={19}/><h2>Your working day</h2></div><form className="small-form" onSubmit={saveSettings} key={`${state.settings.timezone}-${state.settings.workingHoursStart}-${state.settings.workingHoursEnd}`}><Field label="Timezone"><input name="timezone" required defaultValue={state.settings.timezone} placeholder="America/New_York"/></Field><div className="form-grid"><Field label="Starts"><input type="time" name="workingHoursStart" required defaultValue={state.settings.workingHoursStart}/></Field><Field label="Ends"><input type="time" name="workingHoursEnd" required defaultValue={state.settings.workingHoursEnd}/></Field></div><Button type="submit" disabled={!!busy} loading={busy==='settings.update'}>Save working hours</Button></form><div className="settings-toggle-row"><div><strong>Automatic rollover</strong><span>Carry eligible unfinished work forward.</span></div><Toggle label="Automatic rollover" checked={state.settings.rolloverEnabled} disabled={!!busy} onChange={()=>void run('settings.update',{rolloverEnabled:!state.settings.rolloverEnabled})}/></div></section>
    <section className="panel settings-card"><div className="settings-card-heading"><Wallet size={19}/><h2>A sensible budget</h2></div><p className="settings-help">Estimated spend: <strong>{money(state.usage.estimatedCostUsd)}</strong>. Deterministic work does not need model tokens.</p><form className="small-form" key={state.usage.dailyBudgetUsd} onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);await run('usage.update',{dailyBudgetUsd:Number(fd.get('budget'))});}}><Field label="Daily model budget (USD)"><input name="budget" type="number" min="0" max="10000" step="0.01" required defaultValue={state.usage.dailyBudgetUsd}/></Field><Button type="submit" disabled={!!busy} loading={busy==='usage.update'}>Save budget</Button></form></section>
    {state.settings.mode==='demo'&&<button className="reset-demo" onClick={()=>setReset(true)}><RefreshCw size={13}/>Reset this demo workspace</button>}
    </aside></div>
    {scanOpen&&<Modal title="Give Gmail a considered look" subtitle="Track discovered, read, analyzed, skipped, and failed messages." onClose={()=>setScanOpen(false)}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(await run('scan.start',{provider:'gmail',coverage:fd.get('coverage')}))setScanOpen(false);}}><label className="radio-card"><input type="radio" name="coverage" value="selected" defaultChecked disabled={!state.permissions.gmailRead}/><div><strong>Selected messages</strong><span>Scan messages within the configured selection.</span></div></label><label className="radio-card"><input type="radio" name="coverage" value="all" disabled={!state.permissions.gmailRead||!state.permissions.gmailFull}/><div><strong>Full mailbox</strong><span>Requires Gmail read and broad Gmail access.</span></div></label>{!state.permissions.gmailRead&&<p className="inline-help">Enable Gmail read above before starting a scan.</p>}<div className="form-actions"><Button type="button" onClick={()=>setScanOpen(false)}>Cancel</Button><Button type="submit" variant="primary" disabled={!!busy||!state.permissions.gmailRead} loading={busy==='scan.start'}><Search size={14}/>Start scan</Button></div></form></Modal>}
    {disconnect&&<Modal title="Disconnect Google?" subtitle="Connected services will stop receiving new actions." onClose={()=>setDisconnect(false)}><div className="form-stack"><p className="form-copy">Your workspace history remains. You can reconnect and grant the required scopes again whenever you’re ready.</p><div className="form-actions"><Button onClick={()=>setDisconnect(false)}>Stay connected</Button><Button variant="danger" loading={connecting} onClick={async()=>{setConnecting(true);setConnectionError(null);try{await api('/api/google/disconnect',{method:'POST',body:'{}'});setDisconnect(false);setAuthorizationUrl(null);setConnectionMessage('Google disconnected.');await refresh();}catch(e){setConnectionError(e instanceof Error?e.message:'Could not disconnect Google.');setDisconnect(false);}finally{setConnecting(false);}}}><Unplug size={14}/>Disconnect</Button></div></div></Modal>}
    {reset&&<Modal title="Start fresh in demo mode?" subtitle="This resets your synthetic workspace." onClose={()=>setReset(false)}><div className="form-stack"><p className="form-copy">Your demo tasks, conversations, workflows, and activity will be replaced with the starter demo.</p><div className="form-actions"><Button onClick={()=>setReset(false)}>Keep my demo</Button><Button variant="danger" disabled={!!busy} loading={busy==='demo.reset'} onClick={async()=>{if(await run('demo.reset'))setReset(false);}}>Reset demo</Button></div></div></Modal>}
  </>;
}
