import { useState, type FormEvent } from 'react';
import { ArrowRight, CalendarDays, ChevronDown, Clock3, FileText, Mail, Play, RefreshCw, Settings2, ShieldCheck, Sun } from 'lucide-react';
import type { DailyProviderState, DailySource, WorkspaceState } from '../lib/types';
import { Conversations } from './Conversations';
import { CanonicalDaily } from './TaskWorkspace';
import { Badge, Button, EmptyState, Field, Modal, SafeLink, shortDate, shortTime, Toggle, type ScreenProps } from './ui';

const statusLabels: Record<DailyProviderState['status'], string> = { not_connected: 'Not connected', not_enabled: 'Read permission off', idle: 'Not read yet', running: 'Reading', complete: 'Read complete', partial: 'Partial coverage', failed: 'Read failed' };
function sourceStatus(state: WorkspaceState, provider: 'gmail' | 'calendar' | 'drive'): DailyProviderState {
  const snapshot = state.daily?.mode === state.settings.mode ? state.daily.providers.find(item => item.provider === provider) : undefined;
  const permission = state.permissions[provider === 'gmail' ? 'gmailRead' : provider==='drive'?'driveRead':'calendarRead'];
  const connected = state.connections.some(connection => connection.provider === 'google' && connection.connected);
  if (snapshot) return { ...snapshot, status: !permission ? 'not_enabled' : state.settings.mode === 'live' && !connected ? 'not_connected' : snapshot.status };
  return { provider, status: !permission ? 'not_enabled' : state.settings.mode === 'live' && !connected ? 'not_connected' : 'idle', discovered: 0, read: 0, skipped: 0, failed: 0 };
}
export function Daily({ state, run, busy, openAgent, onState, onError, onRequestStatus }: ScreenProps & { openAgent: (id: string) => void; onState: (next: WorkspaceState) => void; onError: (message: string) => void; onRequestStatus?: (pending: boolean) => void }) {
  const [configOpen, setConfigOpen] = useState(false);
  const [sourcesOpen, setSourcesOpen] = useState(false);
  const [selectedSource, setSelectedSource] = useState<DailySource | null>(null);
  const snapshot = state.daily?.mode === state.settings.mode ? state.daily : undefined;
  const config = state.dailyConfig || { enabled: false, time: '09:00', gmailQuery: 'newer_than:1d', calendarId: 'primary' };
  const providers = [sourceStatus(state, 'gmail'), sourceStatus(state, 'calendar'),sourceStatus(state,'drive')];
  const partial = !!snapshot&&providers.some(provider => ['partial','failed'].includes(provider.status));
  const model = state.connections.find(connection => connection.provider === 'model');
  const receipts = state.runs.filter(receipt => snapshot?.receiptIds.includes(receipt.id));
  async function saveConfig(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await run('daily.configure', { enabled: form.get('enabled') === 'on', time: form.get('time'), gmailQuery: form.get('gmailQuery'), calendarId: form.get('calendarId') }); if (result) setConfigOpen(false); }
  return <>
    <div className="page-heading daily-heading"><div><div className="eyebrow"><Sun size={14} />DAILY · {new Date(`${state.today}T12:00:00`).toLocaleDateString('en', { month:'long', day:'numeric', weekday:'long' }).toUpperCase()}</div><h1>Your day, fully in view<span className="heading-dot">.</span></h1><p>Gmail, Calendar, Drive, and your next actions. Start here every day.</p></div><div className="daily-heading-actions"><Button onClick={() => setConfigOpen(true)}><Settings2 size={14} />Daily settings</Button>{partial && <Button loading={busy === 'daily.resume'} disabled={!!busy} onClick={() => void run('daily.resume', { date: state.today })}><Play size={14} />Continue read</Button>}<Button variant="primary" loading={busy === 'daily.run'} disabled={!!busy} onClick={() => void run('daily.run', { date: state.today })}><RefreshCw size={15} />Run Daily now</Button></div></div>
    <div className="daily-provider-grid">{providers.map(provider => { const Icon = provider.provider === 'gmail' ? Mail : provider.provider==='drive'?FileText:CalendarDays; const permission = provider.provider === 'gmail' ? 'gmailRead' : provider.provider==='drive'?'driveRead':'calendarRead'; const good = provider.status === 'complete'; const attention = ['partial','failed'].includes(provider.status); return <section className="panel daily-provider" key={provider.provider}><div className="daily-provider-header"><span className="daily-provider-icon"><Icon size={22} /></span><div><h2>{provider.provider === 'gmail' ? 'Gmail reading' : provider.provider==='drive'?'Drive sources':'Google Calendar'}</h2><span>{provider.provider === 'gmail' ? provider.query || config.gmailQuery : provider.provider==='drive'?'Bound files and references':`Calendar: ${config.calendarId}`}</span></div><Badge tone={good ? 'green' : attention ? 'orange' : 'neutral'} dot>{statusLabels[provider.status]}</Badge></div><div className="daily-read-freshness"><Clock3 size={13} />{provider.lastReadAt ? <>Last actual read {shortDate(provider.lastReadAt)} · {shortTime(provider.lastReadAt,state.settings.timezone)}{snapshot?.mode === 'demo' && <Badge tone="orange">Synthetic</Badge>}</> : 'No read recorded yet'}</div>{provider.error && <p className="daily-provider-error" role="alert">{provider.error}</p>}<div className="daily-provider-counts"><span><strong>{provider.discovered}</strong> discovered</span><span><strong>{provider.read}</strong> read</span><span><strong>{provider.skipped}</strong> skipped</span><span className={provider.failed ? 'text-red' : ''}><strong>{provider.failed}</strong> failed</span></div><div className="daily-provider-footer"><span>{provider.coverage === 'all' ? 'Broad read coverage' : provider.coverage === 'selected' ? 'Selected/query coverage' : provider.provider === 'calendar' ? 'Daily timezone window' : 'Coverage follows query & permissions'}</span>{provider.status === 'not_enabled' ? <button className="text-button" disabled={!!busy} onClick={() => void run('permissions.update', { [permission]: true })}>Enable read<ArrowRight size={12} /></button> : provider.status === 'not_connected' ? <a className="text-button" href="#connections">Connect Google<ArrowRight size={12} /></a> : <Badge>{state.settings.mode}</Badge>}</div></section>; })}</div>
    <section className="panel daily-result"><div className="daily-result-heading"><span><FileText size={18} /></span><div><h2>Latest source-based result</h2><p>{snapshot ? `${shortDate(snapshot.updatedAt)} · ${shortTime(snapshot.updatedAt,snapshot.timezone)} · ${snapshot.sources.length} saved source${snapshot.sources.length === 1 ? '' : 's'}` : 'Run Daily to capture an authorized source snapshot.'}</p></div><Badge tone={snapshot?.mode === 'demo' ? 'orange' : 'neutral'}>{snapshot?.mode === 'demo' ? 'Synthetic snapshot' : 'Direct source reading'}</Badge></div>{snapshot ? <><p className="daily-summary-text">{snapshot.summary || 'Sources were read. No summary text was recorded.'}</p><div className="daily-result-proof"><span><ShieldCheck size={13} />{receipts.length ? `${receipts.reduce((total,receipt) => total+receipt.modelCalls,0)} recorded model calls · ${receipts.reduce((total,receipt) => total+receipt.apiCalls,0)} API calls` : 'No linked usage receipt recorded'}</span>{snapshot.date < state.today && <Badge tone="orange">Previous day · refresh recommended</Badge>}<Button disabled={!!busy||!model?.connected||!snapshot.sources.length} loading={busy==='daily.interpret'} onClick={()=>void run('daily.interpret')}>Interpret with ChatGPT</Button><button className="text-button" onClick={() => setSourcesOpen(!sourcesOpen)} aria-expanded={sourcesOpen}>View actual sources<ChevronDown size={13} /></button></div>{sourcesOpen && <div className="daily-source-list">{snapshot.sources.length ? snapshot.sources.map(source => <button key={source.id} onClick={() => setSelectedSource(source)}><span className="file-symbol">{source.provider === 'gmail' ? <Mail size={17} /> : source.provider === 'calendar' ? <CalendarDays size={17} /> : <FileText size={17} />}</span><span><strong>{source.title}</strong><small>{source.provider} · read {shortTime(source.readAt,snapshot.timezone)}{source.truncated ? ' · bounded excerpt' : ''}</small></span><ArrowRight size={13} /></button>) : <p className="compact-empty">No source content was saved. Review the provider statuses above.</p>}</div>}</> : <div className="daily-first-read"><p>{state.settings.mode === 'demo' ? 'Demo Daily uses fictional messages and events. Real accounts are not read.' : 'Daily remains available while Google is disconnected. Connect the account and enable each read permission to populate this view.'}</p><span>Calendar events remain events; explicit task markers become to-dos.</span></div>}</section>
    <div className="daily-main-grid"><section className="daily-todos"><CanonicalDaily state={state} run={run} busy={busy}/></section><aside className="daily-reading"><div className="daily-reader-label"><div><span className="eyebrow">READ & THINK</span><h2>Your daily conversation</h2></div><Badge tone={model?.connected ? 'green' : 'neutral'}>{model?.connected ? 'Model configured' : 'Model setup pending'}</Badge></div><Conversations state={state} run={run} busy={busy} onState={onState} onError={onError} onRequestStatus={onRequestStatus} compact primaryOnly /><div className="daily-schedule-note"><Clock3 size={15} /><span>{config.enabled ? `Standing read: ${config.time} · ${state.settings.timezone}` : 'Standing reading is off. Run Daily now or set a daily time.'}</span><button className="text-button" onClick={() => setConfigOpen(true)}>Configure</button></div></aside></div>
    {configOpen && <Modal title="A daily rhythm that fits" subtitle="Source reading uses your workspace timezone and independent permissions." onClose={() => setConfigOpen(false)}><form className="form-stack" onSubmit={saveConfig}><label className="checkbox-label"><input name="enabled" type="checkbox" defaultChecked={config.enabled} />Enable a standing daily read</label><Field label="Daily time" hint={`Timezone: ${state.settings.timezone}`}><input type="time" name="time" required defaultValue={config.time} /></Field><Field label="Gmail query" hint="This determines selected coverage. Broad access still requires its own permission."><input name="gmailQuery" required maxLength={500} defaultValue={config.gmailQuery} placeholder="newer_than:1d" /></Field><Field label="Calendar ID"><input name="calendarId" required defaultValue={config.calendarId} placeholder="primary" /></Field><p className="form-copy">Daily reads direct source text and extracts explicit task markers. Interpretation is an explicit step using your connected ChatGPT account.</p><div className="form-actions"><Button type="button" onClick={() => setConfigOpen(false)}>Cancel</Button><Button type="submit" variant="primary" disabled={!!busy} loading={busy === 'daily.configure'}>Save Daily settings<ArrowRight size={14} /></Button></div></form></Modal>}
    {selectedSource && <Modal wide title={selectedSource.title} subtitle={`${selectedSource.provider} source · read ${shortDate(selectedSource.readAt)} at ${shortTime(selectedSource.readAt,state.settings.timezone)}`} onClose={() => setSelectedSource(null)}><div className="form-stack">{selectedSource.truncated && <Badge tone="orange">This is a bounded source excerpt</Badge>}<pre className="daily-source-content">{selectedSource.text || 'No text was recorded for this source.'}</pre><SafeLink url={selectedSource.url}>Open original source</SafeLink><div className="form-actions"><Button onClick={() => setSelectedSource(null)}>Done</Button></div></div></Modal>}
  </>;
}
