import { useState, type FormEvent } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, Clock3, Flag, ListTodo, MoreHorizontal, Pin, Plus, RotateCcw, Sparkles, Sun, Trash2 } from 'lucide-react';
import type { Task, WorkspaceState } from '../lib/types';
import { TaskEditor } from './TaskWorkspace';
import { taskHref, isActiveTask } from './taskViews';
import { rankTaskFeed } from '../lib/domain/feed';
import { TaskFeed, taskNeedsDecision } from './TaskFeed';
import { Avatar, Badge, Button, duration, EmptyState, Field, Modal, SectionHead, shortDate, shortTime, type ScreenProps } from './ui';

export function Today({ state, run, busy, openAgent, onState, onError, onRequestStatus, daily = false, hideHeading = false }: ScreenProps & { openAgent: (id: string) => void; onState: (next: WorkspaceState) => void; onError: (message: string) => void; onRequestStatus?: (pending: boolean) => void; daily?: boolean; hideHeading?: boolean }) {
  const [filter, setFilter] = useState<'today' | 'all' | 'done'>(daily ? 'all' : 'today');
  const [editing, setEditing] = useState<string|null>(null);
  const [showSchedule, setShowSchedule] = useState(true);
  const [rolloverOpen, setRolloverOpen] = useState(false);
  const [rolloverDate, setRolloverDate] = useState(state.today);
  const todayTasks = state.tasks.filter(t => t.plannedDate === state.today&&!t.removedAt&&(isActiveTask(t)||t.status==='done'));
  const open = todayTasks.filter(isActiveTask);
  const done = todayTasks.length - open.length;
  const blocks = state.plan.filter(b => todayTasks.some(t => t.id === b.taskId)).sort((a,b) => a.start.localeCompare(b.start));
  const allocated = blocks.reduce((sum,b) => sum + Math.max(0,(Date.parse(b.end) - Date.parse(b.start)) / 60000),0);
  const estimated = open.reduce((sum,t) => sum + t.estimateMinutes,0);
  const visible = filter === 'done' ? state.tasks.filter(task => task.status === 'done'&&!task.removedAt) : rankTaskFeed(state).filter(isActiveTask).filter(task => filter === 'all' || task.plannedDate <= state.today || (!!task.dueDate && task.dueDate <= state.today) || taskNeedsDecision(state, task));
  const agents = state.agents.filter(a => a.pinned || a.status === 'attention' || todayTasks.some(t => t.agentId === a.id)).slice(0,4);
  const unplanned = open.filter(t => !blocks.some(b => b.taskId === t.id));
  const events = state.events.filter(e => { try { return new Intl.DateTimeFormat('en-CA', { timeZone: state.settings.timezone, year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date(e.start)) === state.today; } catch { return e.start.startsWith(state.today); } });
  return <>
    {!hideHeading && <div className="page-heading"><div><div className="eyebrow"><Sun size={14} />{new Date(`${state.today}T12:00:00`).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</div><h1>Room for what matters<span className="heading-dot">.</span></h1><p>Decisions first. Visible progress. A realistic plan for the rest.</p></div><Button variant="primary" onClick={() => setEditing('new')}><Plus size={17} />Add a task</Button></div>}
    <section className="day-summary" aria-label="Today's overview"><div className="summary-intro"><span className="summary-sun"><Sun size={27} strokeWidth={1.3} /></span><div><span className="eyebrow">YOUR DAY, AT A GLANCE</span><strong>{open.length ? `${open.length} things to move forward` : done ? 'A good day’s work' : 'A fresh start'}</strong><span>{state.settings.workingHoursStart}–{state.settings.workingHoursEnd} · {state.settings.timezone.replace(/_/g,' ')}</span></div></div><div className="summary-stat"><strong>{duration(estimated)}</strong><span>task time</span></div><div className="summary-stat"><strong>{duration(allocated)}</strong><span>in your plan</span></div><div className="summary-stat"><strong>{done}<span className="stat-denominator"> / {todayTasks.length}</span></strong><span>tasks complete</span></div><div className="completion-ring" style={{ background: `conic-gradient(var(--olive) ${todayTasks.length ? done / todayTasks.length * 360 : 0}deg, #e5e7d9 0deg)` }}><span><Check size={18} /></span></div></section>
    <div className={`today-grid ${daily ? 'daily-task-grid' : ''}`}><div className="today-main">
      <section className="panel task-panel"><div className="panel-head"><SectionHead eyebrow={daily ? 'EVERY OPEN LOOP' : 'THE NEXT USEFUL THING'} title={daily ? 'Your full to-do list' : 'Your action feed'} /><div className="segmented" aria-label="Filter tasks">{(['today','all','done'] as const).map(f => <button className={filter === f ? 'selected' : ''} key={f} onClick={() => setFilter(f)}>{f === 'today' ? 'Today' : f === 'all' ? 'All tasks' : 'Done'}</button>)}</div></div>
        {visible.length ? <TaskFeed onRequestStatus={onRequestStatus} tasks={visible} state={state} run={run} busy={busy} editTask={task=>setEditing(task.id)} openAgent={openAgent} onState={onState} onError={onError} /> : <EmptyState icon={ListTodo} title={filter === 'done' ? 'Small wins start here' : 'A little breathing room'}>{filter === 'done' ? 'Completed tasks will collect here as you make progress.' : 'Add a task, or ask an agent to help turn your next goal into steps.'}</EmptyState>}
        <button className="add-task-row" onClick={() => setEditing('new')}><Plus size={16} />Add something to work on<span>One clear next step</span></button>
      </section>
      <section className="panel schedule-panel"><div className="panel-head"><button className="section-toggle" onClick={() => setShowSchedule(!showSchedule)} aria-expanded={showSchedule}><CalendarDays size={19} /><h2>A plan with breathing room</h2><ChevronDown size={16} className={showSchedule ? '' : 'rotated'} /></button><Button variant="ghost" loading={busy === 'plan.generate'} disabled={!!busy} onClick={() => void run('plan.generate', { date: state.today })}><Sparkles size={15} />Build plan</Button></div>
        {showSchedule && <><div className="schedule-intro"><span>Tasks fit around your calendar and working hours.</span><Badge tone="green">Deterministic · no model cost</Badge></div>{!blocks.length && !events.length ? <EmptyState icon={CalendarDays} title="Give your day a shape" action={<Button disabled={!!busy || !open.length} onClick={() => void run('plan.generate', { date: state.today })}>Build today’s plan<ArrowRight size={15} /></Button>}>Add tasks, then let the planner find room for them.</EmptyState> : <div className="schedule-list">{[...blocks.map(b => ({ id: b.id, start: b.start, end: b.end, title: state.tasks.find(t => t.id === b.taskId)?.title || 'Task', type: 'focus' })), ...events.map(e => ({ ...e, type: 'event' }))].sort((a,b) => a.start.localeCompare(b.start)).map(item => <div className={`schedule-block schedule-${item.type}`} key={item.id}><div className="schedule-time">{shortTime(item.start, state.settings.timezone)}<span>{shortTime(item.end, state.settings.timezone)}</span></div><div className="schedule-rail"><i /></div><div className="schedule-info"><span className="eyebrow">{item.type === 'focus' ? 'FOCUS TIME' : 'CALENDAR'}</span><strong>{item.title}</strong></div></div>)}</div>}{unplanned.length > 0 && blocks.length > 0 && <div className="unplanned-note"><Clock3 size={15} /><span>{unplanned.length} task{unplanned.length > 1 ? 's' : ''} outside the current plan. Adjust estimates or move work to another day.</span></div>}<div className="panel-footer"><span><RotateCcw size={13} />Rollover is {state.settings.rolloverEnabled ? 'enabled' : 'off'}</span><button className="text-button" onClick={() => setRolloverOpen(true)}>Review rollover<ArrowRight size={13} /></button></div></>}
      </section>
    </div>{!daily && <aside className="today-aside"><section className="agents-today"><SectionHead eyebrow="WORKING WITH YOU" title="Your people, but agents" /><p className="section-description">The conversations connected to your day.</p>{agents.length ? agents.map(agent => <button className="agent-summary-card" key={agent.id} onClick={() => openAgent(agent.id)}><div className="agent-summary-top"><Avatar agent={agent} /><span className={`agent-state-dot agent-state-${agent.status}`} /><ArrowUpRight size={16} /></div><h3>{agent.name}</h3><p>{agent.summary || agent.description}</p><div className="agent-summary-bottom"><Badge tone={agent.status === 'attention' ? 'orange' : agent.status === 'running' ? 'green' : 'neutral'}>{agent.status === 'attention' ? 'Needs you' : agent.status === 'running' ? 'Working' : agent.status === 'updated' ? 'Updated' : 'Ready when you are'}</Badge>{agent.unread > 0 && <span>{agent.unread} new</span>}</div></button>) : <EmptyState title="Bring an agent into the loop">Agents linked to today’s tasks and pinned conversations will appear here.</EmptyState>}</section><div className="quiet-note"><Sparkles size={19} /><p>Less orchestration.<br /><strong>More actual progress.</strong></p><span>{state.settings.mode === 'demo' ? 'You’re exploring a synthetic workspace. Nothing here sends real messages.' : 'Your connected tools follow the permissions you set.'}</span></div></aside>}</div>
    {editing && <Modal title={editing === 'new' ? 'A clear next step' : 'Task details'} subtitle="Edit the same record used in every task view." onClose={() => setEditing(null)}>{editing==='new'||state.tasks.some(task=>task.id===editing)?<><TaskEditor key={editing} state={state} run={run} busy={busy} task={state.tasks.find(task=>task.id===editing)} onSaved={()=>setEditing(null)} onCancel={()=>setEditing(null)}/>{editing!=='new'&&<div className="form-stack"><a className="text-button" href={taskHref(editing,'#today')} onClick={()=>setEditing(null)}>Context, history & removal<ArrowRight size={13}/></a></div>}</>:<EmptyState title="This task changed or is unavailable">Close and refresh this view.</EmptyState>}</Modal>}
    {rolloverOpen && <Modal title="Carry forward, thoughtfully" subtitle="Move eligible unfinished tasks into a fresh day." onClose={() => setRolloverOpen(false)}><form className="form-stack" onSubmit={async e => { e.preventDefault(); if (await run('plan.rollover', { date: rolloverDate })) setRolloverOpen(false); }}><p className="form-copy">The planner keeps completed work in place and applies your task and rollover rules. Review the resulting plan before starting your day.</p><Field label="Target date"><input type="date" required min={state.today} value={rolloverDate} onChange={e => setRolloverDate(e.target.value)} /></Field><div className="form-actions"><Button type="button" onClick={() => setRolloverOpen(false)}>Cancel</Button><Button variant="primary" type="submit" disabled={!!busy} loading={busy === 'plan.rollover'}><RotateCcw size={15} />Run rollover</Button></div></form></Modal>}
  </>;
}
